### PR TITLE
Adjust to current algorithm

### PR DESCRIPTION
**Pull request by ffluegel**

### CODE REVIEW

**Comment by gfiasco** [comment]
when are we merging this?

**Comment by mary-kate** [comment]
@ffluegel Thank you for the patch! Having tested it, I can somewhat safely say that it works in _most_ circumstances. However, in my testing I found at least one edge case which would cause the script to fail and download zero-byte files: if the downloadable file contains parentheses in its name, it causes bash to whine about "syntax error in expression" on line 66 (of the patched script, obviously). Could you look into fixing this since your bash-fu is strong? :-) Thanks in advance and sorry to be such a naysayer.

@gfiasco Soon, I'd hope, but @img2tab hasn't been active on GitHub since 20 March, so there might be some delays...or in the worst case, they are gone which means an active developer (or better yet, a group of active developer**s**) should fork the repository.

**Comment by ffluegel** [comment]
@mary-kate Thanks for testing. Please try the new version.

**Comment by mary-kate** [comment]
@ffluegel Thanks for the patch, works like a charm! :+1:

**Comment by ffluegel** [comment]
New version for algorithm change today

**Comment by ffluegel** [comment]
Please check my [fork](https://github.com/ffluegel/zippyshare) for the latest update. I'll close this pull request.

**Pull request closed without merging**
